/** Semantic names → emoji-mart ids */
export const EMOJI = {
  wave: 'wave',
  court: 'table_tennis_paddle_and_ball',
  paddle: 'table_tennis_paddle_and_ball',
  ball: 'tennis',
  clipboard: 'clipboard',
  pin: 'round_pushpin',
  bride: 'bride_with_veil',
  groom: 'man_in_tuxedo',
  trophy: 'trophy',
  sparkles: 'sparkles',
  mailbox: 'mailbox_with_no_mail',
  money: 'money_with_wings',
  morning: 'partly_sunny',
  /** Emoji Mart uses `sunny`, not `sun` (sun is missing from the data set). */
  afternoon: 'sunny',
  evening: 'city_sunset',
  night: 'crescent_moon',
  target: 'dart',
  couple: 'couple_with_heart',
  family: 'family',
  handshake: 'handshake',
  fitness: 'muscle',
  hearts: 'two_hearts',
  toast: 'clinking_glasses',
  envelope: 'envelope_with_arrow',
  ribbon: 'ribbon',
  birthday: 'birthday',
  party: 'tada',
  food: 'hamburger',
  music: 'musical_note',
  microphone: 'microphone',
  chat: 'left_speech_bubble',
  bow: 'bow',
}
